package com.bwie.jd_demo.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwie.jd_demo.utils.ProductTitle;

import com.bwie.jd_demo.database.ProductTitleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productTitleDaoConfig;

    private final ProductTitleDao productTitleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productTitleDaoConfig = daoConfigMap.get(ProductTitleDao.class).clone();
        productTitleDaoConfig.initIdentityScope(type);

        productTitleDao = new ProductTitleDao(productTitleDaoConfig, this);

        registerDao(ProductTitle.class, productTitleDao);
    }
    
    public void clear() {
        productTitleDaoConfig.clearIdentityScope();
    }

    public ProductTitleDao getProductTitleDao() {
        return productTitleDao;
    }

}
